'''
9. Faça um programa em Python que desenha uma muralha que possua canhões
apontando para baixo no formato de círculos, cada quadrado deve possuir a
mesma largura de cada segmento é lado. Como mostra a figura abaixo. Note que
a tartaruga deve terminar no mesmo local de origem.
'''

import turtle
turtle.forward(310)
turtle.left(90)
turtle.shape("turtle")
turtle.forward(120)
turtle.left(90)
turtle.forward(120)
turtle.left(90)
turtle.forward(120)
turtle.right(90)
turtle.forward(70)
turtle.right(180)
turtle.circle(20)
turtle.circle(35)
turtle.right(180)
turtle.forward(70)
turtle.right(90)
turtle.forward(120)
turtle.left(90)
turtle.forward(120)
turtle.left(90)
turtle.forward(120)
turtle.right(270)
turtle.forward(70)
turtle.right(180)
turtle.forward(135)
turtle.right(180)
turtle.circle(20)
turtle.circle(35)
turtle.right(180)
turtle.forward(70)
turtle.right(90)
turtle.forward(120)
turtle.left(90)
turtle.forward(120)
turtle.left(90)
turtle.forward(120)
turtle.left(90)
turtle.forward(120)
turtle.right(180)
turtle.forward(120)

turtle.done()